source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

platform :ios, '9.0'

target 'ExReport_Example' do
  pod 'ExReport', :path => '../'
  target 'ExReport_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
